### ISSUE TITLE
Failed to activate the parcel package

### ISSUE THREAD

**Issue by Maxim-Filimonov** [jamescmartinez/parcel#2]
**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [parcel](https://github.com/jamescmartinez/parcel) package, v0.0.3
### Stack Trace

Failed to activate the parcel package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/maxim/dotfiles/.atom/packages/parcel/lib/parcel.coffee:19:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:451:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:430:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:411:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:636:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:95:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      "log",
      "dist"
    ],
    "disabledPackages": [
      "go-plus",
      "term2",
      "filetype-color"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v4.5.7
emmet, v2.3.10
feedback, v0.38.0
language-cjsx, v0.3.0
language-haml, v0.21.0
language-javascript-jsx, v0.3.6
linter, v0.12.6
linter-coffeescript, v0.2.1
linter-js-yaml, v1.0.1
linter-jshint, v0.1.6
linter-ruby, v0.1.6
linter-shellcheck, v0.0.8
meteor-api, v2.19.0
minimap, v4.9.3
parcel, v0.0.3
project-manager, v1.15.8
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by travi** [comment]
I'm having this issue as well, which is preventing any update to the `packages.cson` when I modify installed packages.

**Comment by jamescmartinez** [comment]
Thanks for posting all. I'll take a look this weekend.

**Comment by mwolfindale** [comment]
+1 on Ubuntu 15.04

**Comment by jamescmartinez** [comment]
Fixed in 08d8821.

**Comment by chrishough** [comment]
This issue is still occurring https://github.com/jamescmartinez/parcel/issues/7

**Comment by jamescmartinez** [comment]
@chrishough This project is no longer maintained. Sorry!
